# -*- coding: utf-8 -*-
# All tunables in one place

CONTROL_URL = "http://192.168.137.195:9000/control"
CAMERA_URL  = "http://192.168.137.195:9000/camera"

REQUEST_TIMEOUT = 3
UI_FPS_MS = 33          

TURN_SPEED = 40         
DEADZONE   = 5          

TURN_SPEED_MIN = 15
TURN_SPEED_MAX = 70
SCALE_PX       = 60
SPEED_GAMMA    = 0.8
SPEED_SMOOTH_ALPHA = 0.5
SPEED_UPDATE_DELTA = 2

HOLD_MS = 120
MOUSELOOK_HZ = 60
REPEATER_HZ  = 12

Z_MIN      = 75
Z_MAX      = 110
Z_INITIAL  = 105
SCROLL_Z_STEP = 1   

ATTITUDE_CMD       = "attitude"   
ATTITUDE_AXIS_KEY  = "axis"
ATTITUDE_VALUE_KEY = "value"
AXIS_ROLL  = "r"
AXIS_PITCH = "p"
AXIS_YAW   = "y"

PITCH_MIN = -15
PITCH_MAX =  15
PITCH_INITIAL = 0
PITCH_DEADZONE_PIX   = 3
PITCH_SCALE_PY       = 60
PITCH_GAMMA          = 1.0
PITCH_MAX_STEP_DEG   = 1.2
PITCH_SMOOTH_ALPHA   = 0.5
PITCH_UPDATE_DELTA   = 1

ROLL_MIN = -20
ROLL_MAX =  20
YAW_MIN  = -11
YAW_MAX  =  11

ATT_HOLD_HZ = 60                    
ROLL_YAW_RATE_DPS = 40.0             
ATT_UPDATE_DELTA  = 1.0             
